// Estilos inspirados en Luminous Apothecary
export const t = {
  // Layout
  page: { minHeight: '100vh', background: '#f5f7fa' },
  main: { maxWidth: 1200, margin: '0 auto', padding: '40px 24px 80px' },
  center: { display: 'flex', alignItems: 'center', justifyContent: 'center' },

  // Header
  hdr: {
    background: '#fff',
    padding: '20px 32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottom: '1px solid #e8ecef',
  },
  logo: {
    fontSize: 18,
    fontWeight: 600,
    letterSpacing: '-0.3px',
    textDecoration: 'none',
    color: '#1a1a1a',
  },
  logoAccent: { color: '#5ba3c9' },

  nav: {
    display: 'flex',
    gap: 32,
    alignItems: 'center',
  },
  navLink: {
    fontSize: 14,
    fontWeight: 500,
    color: '#4a5568',
    textDecoration: 'none',
    transition: 'color 0.2s',
  },

  // Hero
  hero: {
    textAlign: 'center',
    marginBottom: 48,
    paddingTop: 24,
  },
  heroTitle: {
    fontSize: 56,
    fontWeight: 800,
    letterSpacing: '-1.5px',
    lineHeight: 1.1,
    marginBottom: 12,
    color: '#1a1a1a',
  },
  heroSubtitle: {
    fontSize: 56,
    fontWeight: 800,
    letterSpacing: '-1.5px',
    lineHeight: 1.1,
    color: '#5ba3c9',
  },

  // Filters
  filterRow: {
    display: 'flex',
    gap: 16,
    marginBottom: 40,
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  filterLabel: {
    fontSize: 11,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.8px',
    color: '#6b7280',
    marginBottom: 8,
  },
  searchBox: {
    flex: 1,
    minWidth: 280,
  },
  searchInput: {
    width: '100%',
    padding: '12px 16px',
    border: '1px solid #d1d5db',
    borderRadius: 8,
    fontSize: 14,
    background: '#fff',
    outline: 'none',
    transition: 'border-color 0.2s',
  },
  select: {
    padding: '12px 16px',
    border: '1px solid #d1d5db',
    borderRadius: 8,
    fontSize: 14,
    background: '#fff',
    color: '#1a1a1a',
    outline: 'none',
    cursor: 'pointer',
    minWidth: 160,
  },

  // Product Grid
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
    gap: 24,
  },

  // Product Card
  card: {
    background: '#fff',
    borderRadius: 12,
    overflow: 'hidden',
    transition: 'transform 0.2s, box-shadow 0.2s',
    border: '1px solid #e8ecef',
  },
  cardHover: {
    transform: 'translateY(-4px)',
    boxShadow: '0 12px 24px rgba(0,0,0,0.08)',
  },
  cardImage: {
    width: '100%',
    height: 280,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: '#f9fafb',
    position: 'relative',
    overflow: 'hidden',
  },
  cardBadge: {
    position: 'absolute',
    top: 12,
    left: 12,
    background: '#fff',
    color: '#5ba3c9',
    fontSize: 10,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    padding: '4px 10px',
    borderRadius: 4,
  },
  cardBody: {
    padding: '20px',
  },
  cardTag: {
    fontSize: 10,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.8px',
    color: '#5ba3c9',
    marginBottom: 8,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: 700,
    marginBottom: 6,
    color: '#1a1a1a',
  },
  cardDesc: {
    fontSize: 13,
    color: '#6b7280',
    lineHeight: 1.5,
    marginBottom: 16,
  },
  cardPrice: {
    fontSize: 20,
    fontWeight: 700,
    color: '#1a1a1a',
    marginBottom: 16,
  },
  cardFooter: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
  },

  // Buttons
  btnPrimary: {
    background: '#5ba3c9',
    color: '#fff',
    border: 'none',
    padding: '12px 24px',
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'background 0.2s',
    flex: 1,
  },
  btnSecondary: {
    background: '#fff',
    color: '#5ba3c9',
    border: '1px solid #5ba3c9',
    padding: '12px 24px',
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  btnGhost: {
    background: 'none',
    color: '#6b7280',
    border: '1px solid #d1d5db',
    padding: '10px 18px',
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 500,
    cursor: 'pointer',
  },
  qtyControl: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    border: '1px solid #d1d5db',
    borderRadius: 8,
    padding: '6px 12px',
    background: '#fff',
  },
  qtyBtn: {
    background: 'none',
    border: 'none',
    color: '#6b7280',
    fontSize: 18,
    fontWeight: 600,
    cursor: 'pointer',
    padding: '0 4px',
    lineHeight: 1,
  },
  qtyValue: {
    fontSize: 15,
    fontWeight: 600,
    minWidth: 24,
    textAlign: 'center',
  },

  // Cart
  cartIcon: {
    position: 'relative',
    cursor: 'pointer',
  },
  cartBadge: {
    position: 'absolute',
    top: -6,
    right: -6,
    background: '#5ba3c9',
    color: '#fff',
    borderRadius: '50%',
    width: 18,
    height: 18,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 10,
    fontWeight: 700,
  },

  // Cart Page
  cartContainer: {
    maxWidth: 1000,
    margin: '0 auto',
    padding: '40px 24px',
  },
  cartTitle: {
    fontSize: 36,
    fontWeight: 800,
    letterSpacing: '-0.5px',
    marginBottom: 8,
  },
  cartSubtitle: {
    fontSize: 15,
    color: '#6b7280',
    marginBottom: 40,
  },
  cartItem: {
    display: 'flex',
    gap: 20,
    padding: '24px',
    background: '#f9fafb',
    borderRadius: 12,
    marginBottom: 16,
  },
  cartItemImage: {
    width: 80,
    height: 80,
    borderRadius: 8,
    background: '#fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  cartItemInfo: {
    flex: 1,
  },
  cartItemTitle: {
    fontSize: 16,
    fontWeight: 600,
    marginBottom: 4,
  },
  cartItemMeta: {
    fontSize: 12,
    color: '#9ca3af',
    marginBottom: 12,
  },
  cartItemPrice: {
    fontSize: 18,
    fontWeight: 700,
    color: '#1a1a1a',
  },
  removeBtn: {
    background: 'none',
    border: 'none',
    color: '#ef4444',
    fontSize: 12,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    cursor: 'pointer',
  },

  // Order Summary
  summary: {
    background: '#fff',
    border: '1px solid #e8ecef',
    borderRadius: 12,
    padding: 32,
    position: 'sticky',
    top: 100,
  },
  summaryTitle: {
    fontSize: 20,
    fontWeight: 700,
    marginBottom: 24,
  },
  summaryRow: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: 12,
    fontSize: 14,
  },
  summaryTotal: {
    display: 'flex',
    justifyContent: 'space-between',
    paddingTop: 16,
    marginTop: 16,
    borderTop: '1px solid #e8ecef',
    fontSize: 11,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.8px',
    color: '#6b7280',
  },
  summaryTotalValue: {
    fontSize: 28,
    fontWeight: 800,
    color: '#1a1a1a',
  },
  checkoutBtn: {
    width: '100%',
    background: '#5ba3c9',
    color: '#fff',
    border: 'none',
    padding: '16px',
    borderRadius: 8,
    fontSize: 15,
    fontWeight: 600,
    cursor: 'pointer',
    marginTop: 24,
    transition: 'background 0.2s',
  },
  ecoLabel: {
    display: 'inline-block',
    background: '#d1fae5',
    color: '#065f46',
    fontSize: 10,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    padding: '4px 8px',
    borderRadius: 4,
    marginLeft: 8,
  },

  // Toast
  toast: {
    position: 'fixed',
    bottom: 32,
    left: '50%',
    transform: 'translateX(-50%)',
    background: '#1a1a1a',
    color: '#fff',
    padding: '14px 28px',
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 500,
    zIndex: 1000,
    boxShadow: '0 8px 24px rgba(0,0,0,0.2)',
  },

  // Admin styles
  adminBadge: {
    background: '#f3f4f6',
    color: '#6b7280',
    fontSize: 11,
    fontWeight: 600,
    padding: '4px 10px',
    borderRadius: 20,
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    background: '#fff',
    borderRadius: 12,
    overflow: 'hidden',
    border: '1px solid #e8ecef',
  },
  th: {
    padding: '14px 20px',
    textAlign: 'left',
    fontSize: 11,
    fontWeight: 600,
    color: '#6b7280',
    textTransform: 'uppercase',
    letterSpacing: '0.8px',
    background: '#f9fafb',
    borderBottom: '1px solid #e8ecef',
  },
  td: {
    padding: '16px 20px',
    fontSize: 14,
    borderBottom: '1px solid #f3f4f6',
    verticalAlign: 'middle',
  },
  btnEdit: {
    background: 'none',
    color: '#5ba3c9',
    border: '1px solid #5ba3c9',
    padding: '6px 14px',
    borderRadius: 6,
    fontSize: 12,
    fontWeight: 600,
    cursor: 'pointer',
    marginRight: 8,
  },
  btnDanger: {
    background: 'none',
    color: '#ef4444',
    border: '1px solid #fecaca',
    padding: '6px 14px',
    borderRadius: 6,
    fontSize: 12,
    fontWeight: 600,
    cursor: 'pointer',
  },
  input: {
    width: '100%',
    border: '1px solid #d1d5db',
    borderRadius: 8,
    padding: '12px 16px',
    fontSize: 14,
    outline: 'none',
    background: '#fff',
    color: '#1a1a1a',
  },
  label: {
    fontSize: 13,
    fontWeight: 600,
    color: '#374151',
    display: 'block',
    marginBottom: 8,
  },
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 200,
    padding: 20,
  },
  modal: {
    background: '#fff',
    borderRadius: 16,
    padding: 32,
    width: '100%',
    maxWidth: 520,
    maxHeight: '90vh',
    overflowY: 'auto',
  },
  pageTitle: {
    fontSize: 32,
    fontWeight: 800,
    letterSpacing: '-0.5px',
    marginBottom: 8,
  },
  pageSub: {
    fontSize: 15,
    color: '#6b7280',
    marginBottom: 32,
  },
  stockBadge(n) {
    return {
      display: 'inline-flex',
      alignItems: 'center',
      padding: '4px 12px',
      borderRadius: 20,
      fontSize: 12,
      fontWeight: 600,
      background: n > 10 ? '#d1fae5' : n > 4 ? '#fef3c7' : '#fee2e2',
      color: n > 10 ? '#065f46' : n > 4 ? '#92400e' : '#991b1b',
    }
  },
}

export const EMOJIS = ['🧴', '🍋', '💪', '🫧', '✨', '🌸', '🧸', '🛡️', '🧹', '🪣', '🫙', '🧽']
export const PALETTE = [
  { bg: '#f0f9ff', col: '#0369a1' },
  { bg: '#f0fdf4', col: '#15803d' },
  { bg: '#fefce8', col: '#a16207' },
  { bg: '#fdf2f8', col: '#be185d' },
  { bg: '#f5f3ff', col: '#7c3aed' },
  { bg: '#fff7ed', col: '#c2410c' },
]
